### ISSUE TITLE
php 8.1 (captcha) Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by julienloizelet** [crowdsecurity/php-cs-bouncer#62]
With PHP 8.1, an error is thrown when a captcha wall has to be displayed.
On my local environment, here is the error : 
```
Fatal error: Uncaught CrowdSecBouncer\BouncerException: Implicit conversion from float 15.5 to int loses precision in /var/www/html/my-own-modules/crowdsec-php-lib/src/StandAloneBounce.php:346 Stack trace: #0 [internal function]: CrowdSecBouncer\StandAloneBounce->CrowdSecBouncer\{closure}(8192, 'Implicit conver...', '/var/www/html/m...', 365) #1 /var/www/html/my-own-modules/crowdsec-php-lib/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php(365): imagettftext(Object(GdImage), 27, -6, 15.5, 36, 6120063, '/var/www/html/m...', 'N') #2 /var/www/html/my-own-modules/crowdsec-php-lib/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php(459): Gregwar\Captcha\CaptchaBuilder->writePhrase(Object(GdImage), 'NVEQO', '/var/www/html/m...', 150, 40) #3 /var/www/html/my-own-modules/crowdsec-php-lib/src/Bouncer.php(227): Gregwar\Captcha\CaptchaBuilder->build() #4 /var/www/html/my-own-modules/crowdsec-php-lib/src/AbstractBounce.php(181): CrowdSecBouncer\Bouncer::buildCaptchaCouple() #5 /var/www/html/my-own-modules/crowdsec-php-lib/src/AbstractBounce.php(246): CrowdSecBouncer\AbstractBounce->storeNewCaptchaCoupleInSession() #6 /var/www/html/my-own-modules/crowdsec-php-lib/src/AbstractBounce.php(267): CrowdSecBouncer\AbstractBounce->handleCaptchaRemediation('172.21.0.1') #7 /var/www/html/my-own-modules/crowdsec-php-lib/src/AbstractBounce.php(124): CrowdSecBouncer\AbstractBounce->handleRemediation('captcha', '172.21.0.1') #8 /var/www/html/my-own-modules/crowdsec-php-lib/src/AbstractBounce.php(60): CrowdSecBouncer\AbstractBounce->bounceCurrentIp() #9 /var/www/html/my-own-modules/crowdsec-php-lib/src/StandAloneBounce.php(348): CrowdSecBouncer\AbstractBounce->run() #10 /var/www/html/my-own-modules/crowdsec-php-lib/examples/auto-prepend/scripts/bounce-via-auto-prepend.php(14): CrowdSecBouncer\StandAloneBounce->safelyBounce() #11 {main} thrown in /var/www/html/my-own-modules/crowdsec-php-lib/src/StandAloneBounce.php on line 346
```

It seems that this is due to the `gregwar/captcha` package:

@see https://github.com/Gregwar/Captcha/issues/100

I'm not sure that the package is still being maintained.

**Comment by julienloizelet** [comment]
FYI, this PR should fix the issue : https://github.com/Gregwar/Captcha/pull/101/files

**Comment by julienloizelet** [comment]
close: https://github.com/crowdsecurity/php-cs-bouncer/pull/63
